
services:
  # === PHP-FPM ===
  php-fpm:
    #build:
    #   context: .
    #   dockerfile: Dockerfile
    image: somchart900/php:8.4-fpm   
    container_name: php-fpm
    restart: always
    volumes:
      - ./project:/var/www/html
      # - ./php-conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    user: root
    command: sh -c "chown -R www-data:www-data /var/www/html/ && php-fpm"  
    depends_on:
      - mysql
      - redis

  # === NGINX ===
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./project:/var/www/html
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  # === MySQL ===
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5     

  # === phpMyAdmin ===
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

  # === Redis ===
  redis:
    image: redis:latest
    container_name: redis
    restart: always
  # ports:
  #   - "6379:6379"
    healthcheck:
       test: ["CMD", "redis-cli", "ping"]
       interval: 30s
       timeout: 10s
       retries: 5
    volumes:
      - redis_data:/data
volumes:
  redis_data:
  mysql_data:
  project:
 